export interface VehicleMakeItem {
  make: string;
  aliases?: string[];
  models: string[];
}

export const VEHICLE_CATALOG: VehicleMakeItem[] = [
  {
    make: "Maruti Suzuki",
    aliases: ["Maruti", "Suzuki", "Maruti-Suzuki", "MSIL"],
    models: [
      "Alto",
      "Alto K10",
      "Baleno",
      "Brezza",
      "Celerio",
      "Ciaz",
      "Dzire",
      "Eeco",
      "Ertiga",
      "Fronx",
      "Grand Vitara",
      "Ignis",
      "Invicto",
      "Jimny",
      "S-Cross",
      "S-Presso",
      "Swift",
      "Vitara Brezza",
      "Wagon R",
      "XL6",
    ],
  },
  {
    make: "Tata",
    aliases: ["Tata Motors", "TML"],
    models: [
      "Altroz",
      "Altroz EV",
      "Curvv",
      "Curvv EV",
      "Harrier",
      "Harrier EV",
      "Hexa",
      "Nano",
      "Nexon",
      "Nexon EV",
      "Punch",
      "Punch EV",
      "Safari",
      "Sierra",
      "Sierra EV",
      "Sumo",
      "Tiago",
      "Tiago EV",
      "Tiago NRG",
      "Tigor",
      "Tigor EV",
      "Zest",
    ],
  },
  {
    make: "Mahindra",
    aliases: ["Mahindra & Mahindra", "M&M", "Mahindraa"],
    models: [
      "Bolero",
      "Bolero Neo",
      "Bolero Neo Plus",
      "KUV100",
      "Marazzo",
      "NuvoSport",
      "Scorpio",
      "Scorpio Classic",
      "Scorpio-N",
      "Thar",
      "Thar Roxx",
      "TUV300",
      "XUV 3XO",
      "XUV300",
      "XUV400",
      "XUV500",
      "XUV700",
      "Xylo",
    ],
  },
  {
    make: "Toyota",
    aliases: ["Toyota Kirloskar", "Toyta"],
    models: [
      "Camry",
      "Corolla",
      "Corolla Altis",
      "Corolla Cross",
      "Etios",
      "Etios Cross",
      "Etios Liva",
      "Fortuner",
      "Fortuner Legender",
      "Glanza",
      "Hilux",
      "Innova",
      "Innova Crysta",
      "Innova Hycross",
      "Land Cruiser",
      "Land Cruiser Prado",
      "Prius",
      "RAV4",
      "Rumion",
      "Supra",
      "Urban Cruiser",
      "Urban Cruiser Hyryder",
      "Urban Cruiser Taisor",
      "Vellfire",
      "Yaris",
    ],
  },
  {
    make: "Honda",
    aliases: ["Honda Cars"],
    models: [
      "Accord",
      "Amaze",
      "BR-V",
      "Brio",
      "CR-V",
      "City",
      "City e:HEV",
      "Civic",
      "Elevate",
      "HR-V",
      "Jazz",
      "Mobilio",
      "WR-V",
    ],
  },
  {
    make: "Hyundai",
    aliases: ["Hyundai Motor", "Hyundia"],
    models: [
      "Accent",
      "Alcazar",
      "Aura",
      "Creta",
      "Creta Electric",
      "Creta N Line",
      "Elantra",
      "Eon",
      "Exter",
      "Grand i10",
      "Grand i10 Nios",
      "Ioniq 5",
      "Ioniq 6",
      "Kona Electric",
      "Palisade",
      "Santa Fe",
      "Santro",
      "Sonata",
      "Tucson",
      "Venue",
      "Venue N Line",
      "Verna",
      "Xcent",
      "i10",
      "i20",
      "i20 Active",
      "i20 N Line",
    ],
  },
  {
    make: "Kia",
    aliases: ["Kia Motors"],
    models: [
      "Carens",
      "Carnival",
      "EV6",
      "EV9",
      "Seltos",
      "Sonet",
      "Sportage",
      "Stinger",
      "Telluride",
    ],
  },
  {
    make: "Ford",
    aliases: ["Ford Motors"],
    models: [
      "Aspire",
      "Bronco",
      "EcoSport",
      "Endeavour",
      "Escape",
      "Everest",
      "Explorer",
      "F-150",
      "Figo",
      "Figo Freestyle",
      "Freestyle",
      "Fusion",
      "Ikon",
      "Mondeo",
      "Mustang",
      "Mustang Mach-E",
      "Ranger",
    ],
  },
  {
    make: "Volkswagen",
    aliases: ["VW", "Volks", "Volkswagon"],
    models: [
      "Ameo",
      "Golf",
      "Golf GTI",
      "ID.4",
      "Jetta",
      "Passat",
      "Polo",
      "Polo GT",
      "T-Cross",
      "T-Roc",
      "Taigun",
      "Tiguan",
      "Tiguan Allspace",
      "Touareg",
      "Vento",
      "Virtus",
    ],
  },
  {
    make: "Skoda",
    aliases: ["Škoda", "Skoda Auto"],
    models: [
      "Fabia",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Kushaq",
      "Kylaq",
      "Laura",
      "Octavia",
      "Octavia RS",
      "Rapid",
      "Slavia",
      "Superb",
      "Yeti",
    ],
  },
  {
    make: "Nissan",
    aliases: ["Nissan Motor"],
    models: [
      "370Z",
      "Altima",
      "Ariya",
      "Evalia",
      "GT-R",
      "Juke",
      "Kicks",
      "Leaf",
      "Magnite",
      "Micra",
      "Micra Active",
      "Pathfinder",
      "Patrol",
      "Qashqai",
      "Rogue",
      "Sentra",
      "Sunny",
      "Terrano",
      "X-Trail",
    ],
  },
  {
    make: "Renault",
    aliases: ["Renault India"],
    models: [
      "Captur",
      "Clio",
      "Duster",
      "Fluence",
      "Kardian",
      "Kiger",
      "Koleos",
      "Kwid",
      "Kwid EV",
      "Lodgy",
      "Megane",
      "Pulse",
      "Scala",
      "Triber",
    ],
  },
  {
    make: "MG",
    aliases: ["Morris Garages", "MG Motor", "MG Motors"],
    models: [
      "Astor",
      "Comet EV",
      "Cyberster",
      "Gloster",
      "Hector",
      "Hector Plus",
      "MG4 EV",
      "MG5 EV",
      "Windsor EV",
      "ZS",
      "ZS EV",
    ],
  },
  {
    make: "Jeep",
    aliases: ["Jeep India"],
    models: [
      "Avenger",
      "Cherokee",
      "Commander",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Meridian",
      "Renegade",
      "Wrangler",
      "Wrangler Rubicon",
    ],
  },
  {
    make: "BMW",
    aliases: ["Bavarian Motor Works", "Bimmer"],
    models: [
      "1 Series",
      "2 Series Gran Coupe",
      "3 Series",
      "3 Series Gran Limousine",
      "4 Series",
      "5 Series",
      "6 Series Gran Turismo",
      "7 Series",
      "8 Series",
      "M2",
      "M3",
      "M4",
      "M5",
      "M8",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z4",
      "i4",
      "i5",
      "i7",
      "iX",
      "iX1",
      "iX3",
    ],
  },
  {
    make: "Mercedes-Benz",
    aliases: ["Mercedes", "Benz", "Merc", "Mercedes Benz", "Mercedez", "Daimler"],
    models: [
      "A-Class",
      "A-Class Limousine",
      "AMG GT",
      "AMG SL",
      "B-Class",
      "C-Class",
      "CLA",
      "CLE",
      "CLS",
      "E-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQE SUV",
      "EQS",
      "EQS SUV",
      "G-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLC Coupe",
      "GLE",
      "GLE Coupe",
      "GLS",
      "Maybach GLS",
      "Maybach S-Class",
      "S-Class",
    ],
  },
  {
    make: "Audi",
    aliases: ["Audi AG"],
    models: [
      "A3",
      "A4",
      "A5",
      "A6",
      "A8",
      "A8 L",
      "Q2",
      "Q3",
      "Q3 Sportback",
      "Q5",
      "Q7",
      "Q8",
      "Q8 e-tron",
      "Q8 Sportback e-tron",
      "RS Q8",
      "RS e-tron GT",
      "RS5",
      "RS7",
      "S5",
      "TT",
      "e-tron",
      "e-tron GT",
    ],
  },
  {
    make: "Tesla",
    aliases: ["Tesla Motors"],
    models: [
      "Cybertruck",
      "Model 3",
      "Model S",
      "Model X",
      "Model Y",
      "Roadster",
      "Semi",
    ],
  },
  {
    make: "Volvo",
    aliases: ["Volvo Cars"],
    models: [
      "C40 Recharge",
      "EX30",
      "EX90",
      "S60",
      "S90",
      "V40",
      "V60",
      "V90",
      "XC40",
      "XC40 Recharge",
      "XC60",
      "XC90",
    ],
  },
  {
    make: "Land Rover",
    aliases: ["Range Rover", "JLR"],
    models: [
      "Defender",
      "Defender 90",
      "Defender 110",
      "Defender 130",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  },
  {
    make: "Porsche",
    aliases: ["Porsche AG"],
    models: [
      "718 Boxster",
      "718 Cayman",
      "911",
      "911 Carrera",
      "911 GT3",
      "911 Turbo",
      "Cayenne",
      "Cayenne Coupe",
      "Macan",
      "Macan EV",
      "Panamera",
      "Taycan",
      "Taycan Cross Turismo",
    ],
  },
];

export type VehicleType = "Car" | "Bike";

export const CAR_CATALOG: VehicleMakeItem[] = VEHICLE_CATALOG;

export const BIKE_CATALOG: VehicleMakeItem[] = [
  {
    make: "Royal Enfield",
    aliases: ["Enfield", "RE", "Royl Enfield"],
    models: [
      "Classic 350",
      "Hunter 350",
      "Bullet 350",
      "Meteor 350",
      "Himalayan",
      "Continental GT 650",
      "Interceptor 650",
    ],
  },
  {
    make: "Honda",
    aliases: ["Honda Motorcycle", "HMSI", "Honnda"],
    models: [
      "Activa 6G",
      "Shine",
      "SP 125",
      "Unicorn",
      "Hornet 2.0",
      "CB350",
    ],
  },
  {
    make: "Yamaha",
    aliases: ["Yamaha Motor", "India Yamaha"],
    models: [
      "R15",
      "MT-15",
      "FZ",
      "FZS",
      "Aerox 155",
    ],
  },
  {
    make: "TVS",
    aliases: ["TVS Motor", "TVS Motor Company"],
    models: [
      "Apache RTR 160",
      "Apache RTR 200",
      "Raider",
      "Jupiter",
      "Ntorq",
    ],
  },
  {
    make: "Bajaj",
    aliases: ["Bajaj Auto"],
    models: [
      "Pulsar 125",
      "Pulsar 150",
      "Pulsar NS200",
      "Dominar 400",
      "Platina",
    ],
  },
  {
    make: "KTM",
    aliases: ["KTM India", "KTM Racing"],
    models: [
      "Duke 125",
      "Duke 200",
      "Duke 250",
      "Duke 390",
      "RC 200",
      "RC 390",
    ],
  },
  {
    make: "Hero",
    aliases: ["Hero MotoCorp", "Hero Honda"],
    models: [
      "Splendor",
      "Passion",
      "Xtreme 125R",
      "Xpulse 200",
      "Karizma",
    ],
  },
  {
    make: "Suzuki",
    aliases: ["Suzuki Motorcycle", "SMIPL"],
    models: [
      "Access 125",
      "Gixxer",
      "Burgman Street",
      "V-Strom SX",
    ],
  },
];

export function getVehicleCatalog(type?: VehicleType | string): VehicleMakeItem[] {
  if (type === "Bike") {
    return BIKE_CATALOG;
  }
  return VEHICLE_CATALOG;
}

export function getAllMakes(type?: VehicleType | string): string[] {
  return [...getVehicleCatalog(type).map((item) => item.make), "Others"];
}

export function getAllModels(type?: VehicleType | string): string[] {
  const catalog = getVehicleCatalog(type);
  const modelsSet = new Set<string>();
  for (const item of catalog) {
    for (const model of item.models) {
      modelsSet.add(model);
    }
  }
  return Array.from(modelsSet).sort((a, b) => a.localeCompare(b));
}

export function getMakeData(makeName: string, type?: VehicleType | string): VehicleMakeItem | undefined {
  const catalog = getVehicleCatalog(type);
  const normalized = makeName.trim().toLowerCase();
  return catalog.find(
    (item) =>
      item.make.toLowerCase() === normalized ||
      item.aliases?.some((alias) => alias.toLowerCase() === normalized)
  );
}

export function getModelsForMake(makeName: string, type?: VehicleType | string): string[] {
  const normalized = makeName.trim().toLowerCase();
  if (normalized === "others" || normalized === "other") {
    return getAllModels(type);
  }
  const makeData = getMakeData(makeName, type);
  return makeData ? makeData.models : [];
}
